Bot was created, connected to telegram, added ability to get message and send the random answer
Y-Pazniak/helloworld_bot pull request #1
Opened 2023-09-13 14:53 UTC by Y-Pazniak

My first chat-bot. It works, while my IDEA running. You can also run it on your machine, if you want. 
To communicate with bot here: https://t.me/helloworld_eugene_bot
I have connected my code with telegram using official Telegram dependency: https://core.telegram.org/bots/tutorial
I am going to improve this test project adding the buttons, check the buttons results and send answer according user choice. 
I have tried to use MVC here - this is the only big technology here.
It works simple: you can write everything you want and he will send you a random message. Designed for emotional support for girls and consists 4 sentences.

2023-09-13 21:18 UTC, MaximPilipeiko requested changes

2023-09-13 21:18 UTC, MaximPilipeiko commented on src/main/java/controller/Bot.java
> +        return "6546426844:AAFuKQt1_phktU0EPGfmzeXAkPl-_B8ou_k";
In the future, please, don't forget to move it to an environment variable. It's not safe to hardcode token in code

2023-09-13 21:18 UTC, MaximPilipeiko commented on src/main/java/model/RandomPhrase.java
> +        ArrayList<String> phrases = new ArrayList<>();
Please, use abstraction instead implementation where it's possible
```suggestion
        List<String> phrases = new ArrayList<>();
```

2023-09-13 21:18 UTC, MaximPilipeiko commented on src/main/java/model/RandomPhrase.java
> +        if (needInit) {
Not bad, but maybe try to make RandomPhrase Singletone?

2023-09-13 21:18 UTC, MaximPilipeiko commented on src/main/java/model/Strings.java
> +public final class Strings {
I think Enum is more suitable to use here.
Strings is too wide name and used in many libraries, even could be in core java(not sure). Try to find a more appropriate word for this domain. Maybe `Answer`, `Advice` e.t.c.

2023-09-13 21:18 UTC, MaximPilipeiko commented on src/main/java/model/Strings.java
> +public final class Strings {
If you decide to use enum, please, will look to collection https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/EnumSet.html

2023-09-14 11:48 UTC, Y-Pazniak commented on src/main/java/controller/Bot.java
> +        return "6546426844:AAFuKQt1_phktU0EPGfmzeXAkPl-_B8ou_k";
I didn't know how to do it, but now I know. Thanks for advice, it is important for real projects. 
https://medium.com/@AlexanderObregon/working-with-environment-variables-in-intellij-idea-a-guide-12876bb796c5

2023-09-14 11:49 UTC, Y-Pazniak commented on src/main/java/model/RandomPhrase.java
> +        ArrayList<String> phrases = new ArrayList<>();
This is the common advice, thank you. But I have forgotten, why do we need to declare this way. I googled it, but i didn't find the complete and proper explanation. There are only advices to do this way. Can you explain me, why it is better to use interface instead class? 

My only thought is easier return: when we declare List<String> we can return everything we want - ArrayList<String> or LinkedList<String>. But is it so important? 

I know, that we need to declare List, it is the law, but I have forgotten this law because I have no idea why it is the best way.

2023-09-14 11:49 UTC, Y-Pazniak commented on src/main/java/model/RandomPhrase.java
> +        if (needInit) {
Yes. This is definitely better. Fixed. 
Need to discuss about Singleton based on static inner class. In theory it looks great, but in praktice it seems not so good and works only from static fields.

2023-09-14 11:49 UTC, Y-Pazniak commented on src/main/java/model/Strings.java
> +public final class Strings {
Thanks for the great advice! I tried to use UNUM here first, but I had some problems here. Probably, I forgot how to work with ENUMs. Fixed. 
"Strings" class name is really dumb with no creative, fixed.

2023-09-18 21:17 UTC, MaximPilipeiko requested changes
Difficult to understand which pull request is accepted to be merged to the main branch. I think only one pull request should exist and the second should be closed as redundant.

2023-09-19 17:56 UTC, Y-Pazniak commented on src/main/java/model/RandomPhraseSingleton.java
> +            return supportPhrasesArray[getRandomNumber()].getPhrase();
Fixed. Thanks for the .values() method remind

2023-09-19 17:56 UTC, closed without merging