The last version of test bot
Y-Pazniak/helloworld_bot pull request #2
Opened 2023-09-14 17:42 UTC by Y-Pazniak

I have leartn how to create bot, to register it, to create the simpliest chats, to create buttons. Now I am ready to create the calculator. I am going to start calculator coding tomorrow. I hope, everything will be fine.

2023-09-18 21:14 UTC, MaximPilipeiko requested changes
Please, apply fixes that we discussed on Sunday

2023-09-18 21:14 UTC, MaximPilipeiko commented on src/main/java/controller/Bot.java
> +        if (message.getText().equals("/start")) {
This simple enhancement will help to avoid NullPointerException
```suggestion
        if ("/start".equals(message.getText())) {
```

2023-09-18 21:14 UTC, MaximPilipeiko commented on src/main/java/model/RandomPhraseSingleton.java
> +        public static final RandomPhraseSingletonHolder SINGLETON_HOLDER = new RandomPhraseSingletonHolder();
Please, fix it as we discuss on Sunday

2023-09-18 21:14 UTC, MaximPilipeiko commented on src/main/java/view/KeyboardMarkup.java
> +    public InlineKeyboardMarkup getInstance() {
It looks strange that `getInstance` returns `InlineKeyboardMarkup` instead `KeyboardMarkup`.
Maybe we `KeyboardMarkup` could inherit `InlineKeyboardMarkup` and make `KeyboardMarkup` singleton?

2023-09-19 18:06 UTC, Y-Pazniak commented on src/main/java/controller/Bot.java
> +        if (message.getText().equals("/start")) {
I don't understand how we can avoid NPE without writing method like 
_private boolean isEmpty (Message message) {
String message = message.getText();
if (message == null || message.isEmpty) {
return true;}
else return false;
}_

How does your solution work?

2023-09-19 18:06 UTC, Y-Pazniak commented on src/main/java/model/RandomPhraseSingleton.java
> +        public static final RandomPhraseSingletonHolder SINGLETON_HOLDER = new RandomPhraseSingletonHolder();
Done. Now singleton works as planned.

2023-09-19 18:08 UTC, Y-Pazniak commented on src/main/java/view/KeyboardMarkup.java
> +    public InlineKeyboardMarkup getInstance() {
I dont have idea what I was trying to do. 
I have madee the better code for this class. Sorry for the mess

2023-09-19 18:09 UTC, merged